#!/usr/bin/python3
# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/master/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import os
import sys
from distutils.version import StrictVersion
import unittest

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))

import testlib
from machine_core import ssh_connection

REGISTRIES_CONF="""
[registries.search]
registries = ['localhost:5000']

[registries.insecure]
registries = ['localhost:5000']
"""

def checkImage(browser, name, owner):
    browser.wait_present("#containers-images > section > table")
    browser.wait_js_func("""(function (first, last) {
        let items = ph_select("#containers-images > section > table tbody");
        for (i = 0; i < items.length; i++)
            if (items[i].innerText.trim().startsWith(first) && items[i].innerText.trim().endsWith(last))
                return true;
        return false;
        })""", name, owner)

@testlib.nondestructive
class TestApplication(testlib.MachineCase):

    def setUp(self):
        super().setUp()
        # backup/restore pristine podman state, so that tests can run on existing testbeds
        self.restore_dir("/var/lib/containers")
        # HACK: sometimes podman leaks mounts
        self.addCleanup(self.machine.execute, "podman rm --force --all && "
            "findmnt --list -otarget | grep /var/lib/containers/. | xargs -r umount || true")

        self.machine.execute("systemctl stop io.podman.service; systemctl --now enable io.podman.socket")

        # Create admin session
        self.machine.execute("""
            mkdir /home/admin/.ssh
            cp /root/.ssh/* /home/admin/.ssh
            chown -R admin:admin /home/admin/.ssh
            chmod -R go-wx /home/admin/.ssh
            """)
        self.admin_s = ssh_connection.SSHConnection(user="admin",
                                                    address=self.machine.ssh_address,
                                                    ssh_port=self.machine.ssh_port,
                                                    identity_file=self.machine.identity_file)

        # Enable user service as well
        self.admin_s.execute("systemctl --user stop io.podman.service; systemctl --now --user enable io.podman.socket")
        self.restore_dir("/home/admin/.local/share/containers")
        self.addCleanup(self.admin_s.execute, "podman rm --force --all")

        self.allow_journal_messages("/run.*/podman/io.podman: couldn't connect.*")

    def execute(self, system, cmd):
        if system:
            return self.machine.execute(cmd)
        else:
            return self.admin_s.execute(cmd)

    def testBasicSystem(self):
        self._testBasic(True)

    def testBasicUser(self):
        self._testBasic(False)

    def _testBasic(self, auth):
        b = self.browser
        m = self.machine

        if not auth:
            self.allow_authorize_journal_messages()
            self.allow_browser_errors("Failed to start system io.podman.socket.*")

        self.login_and_go("/podman", authorized=auth, superuser=auth)
        b.wait_present("#app")

        b.wait_present(".content-filter input")

        # Check all containers
        if auth:
            checkImage(b, "quay.io/libpod/busybox:latest", "system")
            checkImage(b, "quay.io/libpod/alpine:latest", "system")
            checkImage(b, "quay.io/cockpit/registry:2", "system")

        checkImage(b, "quay.io/libpod/busybox:latest", "admin")
        checkImage(b, "quay.io/libpod/alpine:latest", "admin")
        checkImage(b, "quay.io/cockpit/registry:2", "admin")

        # Check order of images
        text = b.text("#containers-images table")
        if auth:
            # all user images before all system images
            self.assertRegex(text, ".*admin.*system.*")
            self.assertNotRegex(text, ".*system.*admin.*")
        else:
            self.assertNotIn("system", text)
        # images are sorted alphabetically
        self.assertRegex(text, ".*cockpit/registry.*libpod/alpine.*libpod/busybox")

        # prepare image ids - much easier to pick a specific container
        images = {}
        for image in self.execute(auth, "podman images --noheading --no-trunc").strip().split("\n"):
            # <name> <tag> sha256:<sha> <other things>
            items = image.split()
            images["{0}:{1}".format(items[0], items[1])] = items[2].split(":")[1]

        # show image listing toggle
        busybox_sel = "#containers-images tbody tr[data-row-id={0}{1}]".format(images["quay.io/libpod/busybox:latest"], auth).lower()
        b.wait_present(busybox_sel)
        b.click(busybox_sel + " td.listing-ct-toggle")
        b.wait_present(busybox_sel + " + tr button.btn-delete")
        b.wait_in_text("#containers-images tbody tr .image-details:first-child:contains('busybox:latest')", "Commandsh")
        b.click(busybox_sel + " td.listing-ct-toggle")

        # make sure no running containers shown
        self.filter_containers('running')
        b.wait_in_text("#containers-containers", "No running containers")

        if auth:
            # Run two containers as system (first exits immediately)
            self.execute(auth, "podman run -d --name test-sh-system alpine sh")
            self.execute(auth, "podman run -d --name swamped-crate-system busybox sleep 1000")

        # Run two containers as admin (first exits immediately)
        self.execute(False, "podman run -d --name test-sh-user alpine sh")
        self.execute(False, "podman run -d --name swamped-crate-user busybox sleep 1000")

        user_containers = {}
        system_containers = {}
        for container in self.execute(True, "podman ps --all --no-trunc").strip().split("\n")[1:]:
            # <sha> <other things> <name>
            items = container.split()
            system_containers[items[-1]] = items[0]
        for container in self.execute(False, "podman ps --all --no-trunc").strip().split("\n")[1:]:
            # <sha> <other things> <name>
            items = container.split()
            user_containers[items[-1]] = items[0]

        # running busybox shown
        if auth:
            b.wait_present("#containers-containers tr th:contains('swamped-crate-system')")
            self.check_container(system_containers["swamped-crate-system"], True, ['swamped-crate-system', 'busybox:latest', 'sleep 1000', 'running'])

        b.wait_present("#containers-containers tr:contains('swamped-crate-user')")
        self.check_container(user_containers["swamped-crate-user"], False, ['swamped-crate-user', 'busybox:latest', 'sleep 1000', 'running'])

        # exited alpine not shown
        b.wait_not_in_text("#containers-containers", "alpine:latest")

        # show all containers and check status
        self.filter_containers('all')

        # exited alpine under everything list
        b.wait_present("#containers-containers")
        if auth:
            self.check_container(system_containers["test-sh-system"], True, ['test-sh-system', 'alpine:latest', 'sh', 'exited'])

        self.check_container(user_containers["test-sh-user"], False, ['test-sh-user', 'alpine:latest', 'sh', 'exited'])

        b.click('#containers-containers tbody tr:contains("swamped-crate-user") td.listing-ct-toggle')
        b.wait_present('#containers-containers tbody tr:contains("swamped-crate-user") + tr button.btn-delete')

        if auth:
            b.click('#containers-containers tbody tr:contains("swamped-crate-system") td.listing-ct-toggle')
            b.wait_present('#containers-containers tbody tr:contains("swamped-crate-system") + tr button.btn-delete')

        # Checked order of containers
        if auth:
            b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "swamped-crate-usertest-sh-userswamped-crate-systemtest-sh-system")
        else:
            b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "swamped-crate-usertest-sh-user")

        # show running container
        self.filter_containers('running')
        if auth:
            self.check_container(system_containers["swamped-crate-system"], True, ['swamped-crate-system', 'busybox:latest', 'sleep 1000', 'running'])
        self.check_container(user_containers["swamped-crate-user"], False, ['swamped-crate-user', 'busybox:latest', 'sleep 1000', 'running'])
        # check exited alpine not in running list
        b.wait_not_in_text("#containers-containers", "alpine:latest")

        # delete running container busybox using force delete
        if auth:
            b.click('#containers-containers tbody tr:contains("swamped-crate-system") + tr button.btn-delete')
            self.confirm_modal("btn-ctr-forcedelete")
            b.wait_not_in_text("#containers-containers", "swamped-crate-system")

        self.filter_containers("all")

        b.click('#containers-containers tbody tr:contains("swamped-crate-user") + tr button.btn-delete')
        self.confirm_modal("btn-ctr-forcedelete")
        b.wait_not_in_text("#containers-containers", "swamped-crate-user")

        b.wait_present('#containers-containers tr:contains("test-sh-user")')
        b.click('#containers-containers tbody tr:contains("test-sh-user") td.listing-ct-toggle')
        b.click('#containers-containers tbody tr:contains("test-sh-user") + tr button.btn-delete')
        self.confirm_modal("btn-ctr-delete")
        b.wait_not_in_text("#containers-containers", "test-sh-user")

        if auth:
            b.wait_present('#containers-containers tr:contains("test-sh-system")')
            b.click('#containers-containers tbody tr:contains("test-sh-system") td.listing-ct-toggle')
            b.click('#containers-containers tbody tr:contains("test-sh-system") + tr button.btn-delete')
            self.confirm_modal("btn-ctr-delete")
            b.wait_not_in_text("#containers-containers", "test-sh-system")

        def container_commit(container_name, image_name="testimg", image_tag="testtag", image_author="tester", image_command="sleep 6000", owner="system"):
            self.filter_containers("all")
            b.wait_present('#containers-containers tr:contains({0})'.format(container_name))
            b.click('#containers-containers tbody tr:contains({0}) td.listing-ct-toggle'.format(container_name))
            # open commit modal and close it using cancel
            b.click('#containers-containers tbody tr:contains({0}) + tr button.btn-commit'.format(container_name))
            self.confirm_modal("btn-ctr-cancel-commit")
            # open commit modal and create an image
            b.click('#containers-containers tbody tr:contains({0}) + tr button.btn-commit'.format(container_name))
            b.wait_present(".modal-dialog div")
            # set commit parameters
            b.set_input_text("#commit-dialog-image-name", image_name)
            b.set_input_text("#commit-dialog-image-tag", image_tag)
            b.set_input_text("#commit-dialog-author", image_author)
            b.set_input_text("#commit-dialog-command", image_command)
            b.click(".modal-dialog div .btn-ctr-commit")
            b.wait_not_present(".modal-dialog div")
            b.wait_present('#containers-images tr:contains("{0}:{1}")'.format(image_name, image_tag))
            checkImage(b, "localhost/{0}:{1}".format(image_name, image_tag), owner)
            # open the listing toggle of testimg and check the commit paramerters
            toggle_sel = '#containers-images tbody tr:contains("{0}:{1}") td.listing-ct-toggle'.format(image_name, image_tag)
            b.click(toggle_sel)
            b.wait_present('#containers-images tbody tr:contains("{0}:{1}"):has(dd:contains("localhost/{0}:{1}"))'.format(image_name, image_tag))
            b.wait_in_text('#containers-images tbody tr:contains("{0}:{1}") dd:nth-child(8)'.format(image_name, image_tag), image_command)
            b.wait_present('#containers-images tbody tr:contains("{0}:{1}"):has(dd:contains({2}))'.format(image_name, image_tag, image_author))
            # close listing toggle again
            b.click(toggle_sel)

        # run a container (will exit immediately) and test the display of commit modal
        if auth:
            self.execute(True, "podman run -d --name test-sh alpine sh")
            container_commit("test-sh")
            checkImage(b, "localhost/testimg:testtag", "system")
            self.execute(True, "podman rm -f test-sh; podman rmi testimg:testtag")

        self.execute(False, "podman run -d --name test-sh alpine sh")
        container_commit("test-sh", owner="admin")
        checkImage(b, "localhost/testimg:testtag", "admin")
        self.execute(False, "podman rm -f test-sh; podman rmi testimg:testtag")

        # test commit of a running container
        if auth:
            self.execute(True, "podman run -d --name test-sh busybox sleep 1000")
            container_commit("test-sh", image_command=r'sh -c "while echo \"Hello World\"; do sleep 1; done "')
            self.execute(True, "podman rm -f test-sh; podman rmi testimg:testtag")

        # HACK - this does not work, see https://github.com/containers/libpod/issues/3970
        # self.execute(False, "podman run -d --name test-sh alpine sleep 1000")
        # container_commit("test-sh", owner="admin")
        # self.execute(False, "podman rm -f test-sh; podman rmi testimg:testtag")

        if auth:
            self.execute(True, "podman run -d --name test-sh alpine sh")
        else:
            self.execute(False, "podman run -d --name test-sh alpine sh")
        b.wait_present('#containers-containers tr:contains("alpine:latest")')
        b.click('#containers-containers tbody tr:contains("alpine:latest") td.listing-ct-toggle')
        # open commit modal and check error modal
        b.click('#containers-containers tbody tr:contains("alpine:latest") + tr button.btn-commit')
        # check required field error
        b.click(".modal-dialog div .btn-ctr-commit")
        b.wait_present('.modal-dialog div:contains("Image name is required")')
        b.click(".modal-dialog div .pf-c-alert .pf-c-button")
        b.wait_not_present(".modal-dialog div .alert")

        # check varlink error
        b.set_input_text("#commit-dialog-image-name", "TEST")
        b.click(".modal-dialog div .btn-ctr-commit")
        b.wait_present('.modal-dialog div:contains("io.podman.ErrorOccurred")')
        b.click(".modal-dialog div .pf-c-alert .pf-c-button")
        b.wait_not_present(".modal-dialog div .alert")
        b.wait_present(".modal-dialog div .btn-ctr-commit:not([disabled])")

        b.click(".btn-ctr-cancel-commit")

        # delete image busybox that hasn't been used
        b.wait_present(busybox_sel)
        b.click(busybox_sel + " td.listing-ct-toggle")
        b.click(busybox_sel + " + tr button.btn-delete")
        b.click(".modal-dialog div #btn-img-delete")
        b.wait_not_present("modal-dialog div #btn-img-delete")
        b.wait_not_in_text("#containers-images", busybox_sel)

        # delete image alpine that has been used by a container
        alpine_sel = "#containers-images tbody tr[data-row-id={0}{1}]".format(images["quay.io/libpod/alpine:latest"], auth).lower()
        b.wait_present(alpine_sel)
        b.click(alpine_sel + " td.listing-ct-toggle")
        b.click(alpine_sel + " + tr button.btn-delete")
        b.click(".modal-dialog div #btn-img-delete")
        b.wait_not_present("modal-dialog div #btn-img-delete")
        b.click(".modal-dialog div #btn-img-deleteerror")
        b.wait_not_present("modal-dialog div #btn-img-deleteerror")
        b.wait_not_in_text("#containers-images", alpine_sel)

        b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "")
        self.execute(auth, "podman run -d --name c registry:2 sh")
        b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "c")
        self.execute(auth, "podman run -d --name a registry:2 sh")
        b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "ac")

        self.execute(False, "podman run -d --name b registry:2 sh")
        if auth:
            b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "bac")
            self.execute(False, "podman run -d --name d registry:2 sh")
            b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "bdac")
        else:
            b.wait_collected_text("#containers-containers table > tbody th:nth-child(2)", "abc")

    def testDownloadImage(self):
        b = self.browser
        m = self.machine
        execute = self.execute

        def prepare():
            # Create and start registry container
            self.execute(True, "podman run -d -p 5000:5000 --name registry registry:2")
            # Add local insecure registry into resgitries conf
            self.execute(True, "echo \"{0}\" > /etc/containers/registries.conf && systemctl stop io.podman.service".format(REGISTRIES_CONF))
            # Push busybox image to the local registry
            self.execute(True, "podman tag quay.io/libpod/busybox localhost:5000/my-busybox && podman push localhost:5000/my-busybox")
            # Untag busybox image which duplicates the image we are about to download
            self.execute(True, "podman rmi -f quay.io/libpod/busybox")
            self.execute(False, "podman rmi -f quay.io/libpod/busybox")

        class DownloadImageDialog:
            def __init__(self, imageName, imageTag=None, user="system"):
                self.imageName = imageName
                self.imageTag = imageTag
                self.user = user
                self.imageSha = ""

            def openDialog(self):
                # Open get new image modal
                b.click("header a:contains(Get new image)")
                b.wait_present('div.modal-dialog div.modal-header h4.modal-title:contains("Search Image")')
                b.wait_present("div.modal-dialog div.modal-footer button:contains(Download):disabled")

                return self

            def fillDialog(self):
                # Search for image specied with self.imageName and self.imageTag
                b.click("#{0}".format(self.user))
                b.set_input_text("#search-image-dialog-name", self.imageName)
                if self.imageTag:
                    b.set_input_text(".image-tag-entry", self.imageTag)

                return self

            def selectImageAndDownload(self):
                # Select and download the self.imageName image
                b.wait_present("div.list-group .image-list-item label:contains({0})".format(self.imageName))
                b.click("div.list-group .image-list-item label:contains({0})".format(self.imageName))
                b.wait_present("div.modal-dialog div.modal-footer button:contains(Download):not([disabled])")
                b.click("div.modal-dialog div.modal-footer button:contains(Download)")

                return self

            def expectDownloadErrorForNonExistingTag(self):
                b.wait_not_present('div.modal-dialog')
                b.wait_present('h4.pf-c-alert__title:contains("Danger alert:Failed to download image localhost:5000/{0}:{1}")'.format(self.imageName, self.imageTag))

                return self

            def expectSearchErrorForNotExistingImage(self):
                b.wait_present("div.modal-body:contains(No results for {0})".format(self.imageName))

                return self

            def expectDownloadSuccess(self):
                # Confirm that the modal dialog is not open anymore
                b.wait_not_present('div.modal-dialog')
                # Confirm that the image got downloaded
                b.wait_present('#containers-images tr:contains("{0}")'.format(self.imageName))
                checkImage(b, "localhost:5000/{0}:{1}".format(self.imageName, self.imageTag or "latest"), "system" if self.user == "system" else "admin")

                # Find out this image ID
                self.imageSha = execute(self.user == "system", "podman inspect --format '{{{{.Id}}}}' {0}:{1}".format(self.imageName, self.imageTag or "latest")).strip()

                return self

            def deleteImage(self):
                if self.imageTag:
                    imageTagSuffix =  ":" + self.imageTag
                else:
                    imageTagSuffix = ""

                # Select the image row

                # show image listing toggle
                sel = "#containers-images tbody tr[data-row-id={0}{1}]".format(self.imageSha, "true" if self.user == "system" else "false")
                b.wait_present(sel)
                b.click(sel + " td.listing-ct-toggle")

                # Click the delete icon on the image row
                b.wait_present(sel + ' + tr button.btn-delete')
                b.click(sel +' + tr button.btn-delete')

                # Confirm deletion in the delete dialog
                b.click(".modal-dialog div #btn-img-delete")

                b.wait_not_present(sel)

                return self

        prepare()

        self.login_and_go("/podman")
        b.wait_present("#app")

        dialog0 = DownloadImageDialog('my-busybox', user="system")
        dialog0.openDialog() \
              .fillDialog() \
              .selectImageAndDownload() \
              .expectDownloadSuccess()

        dialog1 = DownloadImageDialog('my-busybox', user="user")
        dialog1.openDialog() \
              .fillDialog() \
              .selectImageAndDownload() \
              .expectDownloadSuccess()
        dialog1.deleteImage()

        dialog0.deleteImage()

        dialog = DownloadImageDialog('my-busybox', 'latest', user="system")
        dialog.openDialog() \
              .fillDialog() \
              .selectImageAndDownload() \
              .expectDownloadSuccess() \
              .deleteImage()

        dialog = DownloadImageDialog('foobar')
        dialog.openDialog() \
              .fillDialog() \
              .expectSearchErrorForNotExistingImage()

        dialog = DownloadImageDialog('my-busybox', 'foobar')
        dialog.openDialog() \
              .fillDialog() \
              .selectImageAndDownload() \
              .expectDownloadErrorForNonExistingTag()

    def testLifecycleOperationsUser(self):
        self._testLifecycleOperations(False)

    def testLifecycleOperationsSystem(self):
        self._testLifecycleOperations(True)

    def _testLifecycleOperations(self, auth):
        b = self.browser
        m = self.machine

        if not auth:
            self.allow_authorize_journal_messages()
            self.allow_browser_errors("Failed to start system io.podman.socket.*")

        # run a container
        self.execute(auth, "podman run -dit --name swamped-crate busybox sh; podman stop swamped-crate")
        b.wait(lambda: self.execute(auth, "podman ps --all | grep -e swamped-crate -e Exited"))

        self.login_and_go("/podman", authorized=auth, superuser=auth)
        b.wait_present("#app")
        self.filter_containers('all')

        b.wait_present("#containers-containers")
        b.wait_present('#containers-containers tr:contains("swamped-crate")')
        b.click('#containers-containers tbody tr:contains("busybox:latest") td.listing-ct-toggle')

        # Start the container
        b.click('#containers-containers tbody tr:contains("busybox:latest") + tr button:contains(Start)')

        container_sha = self.execute(auth, "podman inspect --format '{{.Id}}' swamped-crate").strip()

        with b.wait_timeout(5):
            self.check_container(container_sha, auth, ['swamped-crate', 'busybox:latest', 'sh', 'running', "system" if auth else "admin"])
        # Check we show usage
        b.wait(lambda: b.text("#containers-containers tbody tr:contains('busybox:latest') > td:nth-child(5)") != "")
        cpu = b.text("#containers-containers tbody tr:contains('busybox:latest') > td:nth-child(5)")
        memory = b.text("#containers-containers tbody tr:contains('busybox:latest') > td:nth-child(6)")
        if auth or m.image not in ["rhel-8-2", "rhel-8-3"]:
            self.assertIn('%', cpu)
            num = cpu[:-1]
            self.assertTrue(num.replace('.', '', 1).isdigit())

            self.assertIn('/', memory)
            numbers = memory.split('/')
            self.assertTrue(numbers[0].strip().replace('.', '', 1).isdigit())
            full = numbers[1].strip().split()
            self.assertTrue(full[0].replace('.', '', 1).isdigit())
            self.assertIn(full[1], ["GiB", "MiB"])
        else:
            # No support for CGroupsV2
            self.assertEqual(cpu, "n/a")
            self.assertEqual(memory, "n/a")

        # Restart the container
        old_pid = self.execute(auth, "podman inspect --format '{{.State.Pid}}' swamped-crate")
        b.click('#containers-containers tbody tr:contains("busybox:latest") + tr button:contains(Restart) + button')
        b.click('#containers-containers tbody tr:contains("busybox:latest") + tr ul.pf-c-dropdown__menu li a:contains(Force Restart)')
        b.wait(lambda: old_pid != self.execute(auth, "podman inspect --format '{{.State.Pid}}' swamped-crate".strip()))

        with b.wait_timeout(5):
            self.check_container(container_sha, auth, ['swamped-crate', 'busybox:latest', 'sh', 'running'])

        self.filter_containers('all')
        b.wait_present("#containers-containers")

        # Stop the container
        b.wait_present('#containers-containers tr:contains("busybox:latest")')
        b.click('#containers-containers tbody tr:contains("busybox:latest") + tr button:contains(Stop) + button')
        b.click('#containers-containers tbody tr:contains("busybox:latest") + tr ul.pf-c-dropdown__menu li a:contains(Force Stop)')

        self.check_container(container_sha, auth, ['swamped-crate', 'busybox:latest', 'sh'])
        b.wait(lambda: b.text('#containers-containers tr:contains(swamped-crate) td:nth-of-type(7)') in ['stopped', 'exited'])
        b.wait_text("#containers-containers tbody tr:contains('busybox:latest') > td:nth-child(5)", "")
        b.wait_text("#containers-containers tbody tr:contains('busybox:latest') > td:nth-child(6)", "")

    def testNotRunning(self):
        b = self.browser
        m = self.machine

        def disable_system():
            self.execute(True, "systemctl disable --now io.podman.socket")
            self.execute(True, "killall podman || true")

        def enable_system():
            self.execute(True, "systemctl enable --now io.podman.socket")

        def enable_user():
            self.execute(False, "systemctl --user enable --now io.podman.socket")

        def disable_user():
            self.execute(False, "systemctl --user disable --now io.podman.socket")
            self.execute(False, "killall podman || true")

        def is_active_system(string):
            b.wait(lambda: self.execute(True, "systemctl is-active io.podman.socket || true").strip() == string)

        def is_enabled_system(string):
            b.wait(lambda: self.execute(True, "systemctl is-enabled io.podman.socket || true").strip() == string)

        def is_active_user(string):
            b.wait(lambda: self.execute(False, "systemctl --user is-active io.podman.socket || true").strip() == string)

        def is_enabled_user(string):
            b.wait(lambda: self.execute(False, "systemctl --user is-enabled io.podman.socket || true").strip() == string)

        disable_system()
        disable_user()
        self.login_and_go("/podman")

        # Troubleshoot action
        b.click("#app .pf-c-empty-state button.pf-m-link")
        b.enter_page("/system/services")
        b.wait_in_text("#service-details", "io.podman.socket")

        # Start action, with enabling (by default)
        b.go("/podman")
        b.enter_page("/podman")
        b.click("#app .pf-c-empty-state button.pf-m-primary")

        b.wait_present("#containers-containers")
        b.wait_not_present("#overview > div.pf-c-alert.pf-m-info")

        is_active_system("active")
        is_active_user("active")
        is_enabled_system("enabled")
        is_enabled_user("enabled")

        # Start action, without enabling
        disable_system()
        disable_user()
        b.click("#app .pf-c-empty-state input[type=checkbox]")
        b.click("#app .pf-c-empty-state button.pf-m-primary")

        b.wait_present("#containers-containers")
        is_enabled_system("disabled")
        is_enabled_user("disabled")
        is_active_system("active")
        is_active_user("active")

        b.logout()
        disable_system()
        enable_user()
        self.login_and_go("/podman")
        b.wait_in_text("#overview div.pf-c-alert .pf-c-alert__title", "System Podman service is also available")
        b.click("#overview div.pf-c-alert .pf-c-alert__action > button:contains(Start)")
        b.wait_not_present("#overview div.pf-c-alert")
        is_active_system("active")
        is_active_user("active")
        is_enabled_user("enabled")
        is_enabled_system("enabled")

        b.logout()
        disable_user()
        enable_system()
        self.login_and_go("/podman")
        b.wait_in_text("#overview div.pf-c-alert .pf-c-alert__title", "User Podman service is also available")
        b.click("#overview div.pf-c-alert .pf-c-alert__action > button:contains(Start)")
        b.wait_not_present("#overview > div.pf-c-alert")
        is_active_system("active")
        is_active_user("active")
        is_enabled_user("enabled")
        is_enabled_system("enabled")

        b.logout()
        disable_user()
        disable_system()
        self.login_and_go("/podman", authorized=False, superuser=False)
        b.click("#app .pf-c-empty-state button.pf-m-primary")

        b.wait_present("#containers-containers")
        b.wait_not_present("#overview div.pf-c-alert")
        is_active_system("inactive")
        is_active_user("active")
        is_enabled_user("enabled")
        is_enabled_system("disabled")

        self.allow_restart_journal_messages()
        self.allow_authorize_journal_messages()

    def testRunImageSystem(self):
        self._testRunImage(True)

    def testRunImageUser(self):
        self.allow_authorize_journal_messages()
        self._testRunImage(False)

    def _testRunImage(self, auth):
        b = self.browser
        m = self.machine

        if auth:
            # Just drop user containers so we can user simpler selectors
            self.execute(False, "podman rmi alpine busybox registry:2")

        self.login_and_go("/podman", authorized=auth, superuser=auth)
        b.wait_in_text("#containers-images", "busybox:latest")
        b.wait_in_text("#containers-images", "alpine:latest")

        # Check command in alpine
        b.wait_present('#containers-images tr:contains("alpine:latest")')
        b.click('#containers-images tbody tr:contains("alpine:latest") td.listing-ct-actions button')
        b.wait_present('div.modal-dialog div.modal-header h4.modal-title:contains("Run Image")')
        b.wait_present("#run-image-dialog-command[value='/bin/sh']")
        b.click(".btn-cancel")

        # Open run image dialog
        b.wait_present('#containers-images tr:contains("busybox:latest")')
        b.click('#containers-images tbody tr:contains("busybox:latest") td.listing-ct-actions button')
        b.wait_present('div.modal-dialog div.modal-header h4.modal-title:contains("Run Image")')

        # Inspect and fill modal dialog
        b.wait_in_text("#run-image-dialog-image", "busybox:latest")

        # Check that there is autogenerated name and then overwrite it
        b.wait_not_val("#run-image-dialog-name", "")
        b.set_input_text("#run-image-dialog-name", "busybox-with-tty")

        b.wait_present("#run-image-dialog-command[value='sh']")

        # Check memory configuration
        # Only works with CGroupsV2
        if auth or m.image not in ["rhel-8-2", "rhel-8-3"]:
            b.set_checked("#run-image-dialog-memory-limit-checkbox", True)
            b.wait_present("#run-image-dialog-memory-limit-checkbox:checked")
            b.wait_present('div.modal-body label:contains("Memory Limit") + div.form-inline > input[value="512"]')
            b.set_input_text("#run-image-dialog-memory-limit input.form-control", "0.5")
            b.set_val('#memory-unit-select', "GiB")

        # CPU shares work only with system containers
        if auth:
            b.set_checked("#run-image-dialog-cpu-priority-checkbox", True)
            b.wait_present("#run-image-dialog-cpu-priority-checkbox:checked")
            b.wait_present('div.modal-body label:contains("CPU Shares") + div.form-inline > input[value=""]')
            b.set_input_text("#run-image-dialog-cpu-priority input.form-control", "512")
        else:
            b.wait_not_present("#run-image-dialog-cpu-priority-checkbox")

        # Enable tty
        b.set_checked("#run-image-dialog-tty", True)

        # Set up command line
        b.set_input_text('#run-image-dialog-command', "sh -c 'for i in $(seq 20); do sleep 1; echo $i; done; sleep infinity'")

        # Configure published ports
        b.set_input_text('.publish-port-form[data-key="0"] input:first-child', '5000')
        b.set_input_text('.publish-port-form[data-key="0"] input:nth-child(2)', '6000')
        b.click('.publish-port-form[data-key="0"] .btn-add')
        b.set_input_text('.publish-port-form[data-key="1"] input:first-child', '5001')
        b.set_input_text('.publish-port-form[data-key="1"] input:nth-child(2)', '6001')
        b.set_val('.publish-port-form[data-key="1"] select', "UDP")
        b.click('.publish-port-form[data-key="1"] .btn-add')
        b.set_input_text('.publish-port-form[data-key="2"] input:first-child', '7001')
        b.set_input_text('.publish-port-form[data-key="2"] input:nth-child(2)', '7001')
        b.click('.publish-port-form[data-key="2"] .btn-close')
        b.click('.publish-port-form[data-key="1"] .btn-add')
        b.set_input_text('.publish-port-form[data-key="3"] input:first-child', '8001')
        b.set_input_text('.publish-port-form[data-key="3"] input:nth-child(2)', '8001')

        # Configure env
        b.set_input_text('.env-form[data-key="0"] input:first-child', 'APPLE')
        b.set_input_text('.env-form[data-key="0"] input:last-child', 'ORANGE')
        b.click('.env-form[data-key="0"] .btn-add')
        b.set_input_text('.env-form[data-key="1"] input:first-child', 'PEAR')
        b.set_input_text('.env-form[data-key="1"] input:last-child', 'BANANA')
        b.click('.env-form[data-key="1"] .btn-add')
        b.set_input_text('.env-form[data-key="2"] input:first-child', 'MELON')
        b.set_input_text('.env-form[data-key="2"] input:last-child', 'GRAPE')
        b.click('.env-form[data-key="2"] .btn-close')
        b.click('.env-form[data-key="1"] .btn-add')
        b.set_input_text('.env-form[data-key="3"] input:first-child', 'RHUBARB')
        b.set_input_text('.env-form[data-key="3"] input:last-child', 'STRAWBERRY')

        # Configure volumes
        rodir, rwdir = m.execute("mktemp; mktemp").split('\n')[:2]
        b.set_val('.volume-form[data-key="0"] select', "ro")
        b.set_input_text('.volume-form[data-key="0"] .form-group > div > div > input', rodir)
        b.set_input_text('.volume-form[data-key="0"] > div > input', '/tmp/ro')
        b.wait_val('.volume-form[data-key="0"] .form-group > div > div > input', rodir)
        b.wait_not_present('.volume-form[data-key="0"] .pending-callback')
        b.click('.volume-form[data-key="0"] .btn-add')
        b.click('.volume-form[data-key="1"] .btn-close')
        b.wait_not_present('.volume-form[data-key="1"]')
        b.click('.volume-form[data-key="0"] .btn-add')
        b.set_input_text('.volume-form[data-key="2"] .form-group > div > div > input', rwdir)
        b.set_input_text('.volume-form[data-key="2"] > div > input', '/tmp/rw')
        b.wait_val('.volume-form[data-key="2"] .form-group > div > div > input', rwdir)
        b.wait_not_present('.volume-form[data-key="2"] .pending-callback')

        b.click('div.modal-footer button:contains("Run")')
        b.wait_not_present("div.modal-dialog")
        b.wait_present('#containers-containers tr:contains("busybox:latest")')
        sha = self.execute(auth, "podman inspect --format '{{.Id}}' busybox-with-tty").strip()
        self.check_container(sha, auth, ['busybox-with-tty', 'busybox:latest', 'sh -c "for i in $(seq 20); do sleep 1; echo $i; done; sleep infinity"', 'running', "system" if auth else "admin"])
        hasTTY = self.execute(auth, "podman inspect --format '{{.Config.Tty}}' busybox-with-tty").strip()
        self.assertEqual(hasTTY, 'true')
        # Only works with CGroupsV2
        if auth or m.image not in ["rhel-8-2", "rhel-8-3"]:
            memory = self.execute(auth, "podman inspect --format '{{.HostConfig.Memory}}' busybox-with-tty").strip()
            self.assertEqual(memory, '536870912')

        if auth:
            cpuShares = self.execute(auth, "podman inspect --format '{{.HostConfig.CpuShares}}' busybox-with-tty || podman inspect --format '{{.HostConfig.CPUShares}}' busybox-with-tty").strip()
            self.assertEqual(cpuShares, '512')

        b.wait(lambda: "3" in self.execute(auth, "podman logs busybox-with-tty"))

        b.click('#containers-containers tbody tr:contains("busybox:latest") td.listing-ct-toggle')

        b.wait_in_text('#containers-containers tr:contains("busybox:latest") dt:contains("Ports") + dd', '0.0.0.0:6000 \u2192 5000/tcp')
        b.wait_in_text('#containers-containers tr:contains("busybox:latest") dt:contains("Ports") + dd', '0.0.0.0:6001 \u2192 5001/udp')
        b.wait_in_text('#containers-containers tr:contains("busybox:latest") dt:contains("Ports") + dd', '0.0.0.0:8001 \u2192 8001/tcp')
        b.wait_not_in_text('#containers-containers tr:contains("busybox:latest") dt:contains("Ports") + dd', '0.0.0.0:7001 \u2192 7001/tcp')
        ports = self.execute(auth, "podman inspect --format '{{.NetworkSettings.Ports}}' busybox-with-tty")
        self.assertIn('5000/tcp:[{ 6000}]', ports)
        self.assertIn('5001/udp:[{ 6001}]', ports)
        self.assertIn('8001/tcp:[{ 8001}]', ports)
        self.assertNotIn('7001/tcp:[{ 7001}]', ports)

        env = self.execute(auth, "podman exec busybox-with-tty env")
        self.assertIn('APPLE=ORANGE', env)
        self.assertIn('PEAR=BANANA', env)
        self.assertIn('RHUBARB=STRAWBERRY', env)
        self.assertNotIn('MELON=GRAPE', env)

        romnt = self.execute(auth, "podman exec busybox-with-tty cat /proc/self/mountinfo | grep /tmp/ro")
        self.assertIn('ro', romnt)
        self.assertIn(rodir[4:], romnt)
        rwmnt = self.execute(auth, "podman exec busybox-with-tty cat /proc/self/mountinfo | grep /tmp/rw")
        self.assertIn('rw', rwmnt)
        self.assertIn(rwdir[4:], rwmnt)

        def get_int(n):
            try:
                return int(n)
            except ValueError:
                return 0

        b.click("a:contains('Logs')")
        b.wait_text(".container-logs .xterm-accessibility-tree > div:nth-child(1)", "1")
        b.wait_text(".container-logs .xterm-accessibility-tree > div:nth-child(6)", "6")

        b.click("a:contains('Console')")
        b.wait(lambda: get_int(b.text(".container-terminal .xterm-accessibility-tree > div:nth-child(3)")) > 7)

        # HACK: Stop this container because of https://github.com/containers/libpod/issues/3454
        b.click('#containers-containers tbody tr:contains("busybox-with-tty") + tr button:contains(Stop) + button')
        b.click("div.pf-c-dropdown.pf-m-expanded ul li:nth-child(1) a")

        # Create another instance without port publishing
        b.wait_present('#containers-images tr:contains("busybox:latest")')
        b.click('#containers-containers tbody tr:contains("busybox:latest") td.listing-ct-toggle')
        b.click('#containers-images tbody tr:contains("busybox:latest") td.listing-ct-actions button')
        b.wait_present('div.modal-dialog div.modal-header h4.modal-title:contains("Run Image")')

        b.wait_in_text("#run-image-dialog-image", "busybox:latest")
        b.set_input_text("#run-image-dialog-name", "busybox-without-publish")

        # Set up command line
        b.set_input_text('#run-image-dialog-command', '/bin/sh')

        b.click('div.modal-footer button:contains("Run")')
        b.wait_not_present("div.modal-dialog")
        b.wait_present('#containers-containers tr:contains("busybox-without-publish")')
        b.click('#containers-containers tbody tr:contains("busybox-without-publish") td.listing-ct-toggle')
        b.wait_present('#containers-containers tbody tr:contains("busybox-without-publish") + tr dt:contains("Ports")')
        b.wait_text('#containers-containers tr:contains("busybox-without-publish") + tr dt:contains("Ports") + dd', "")

        # Rootless only works with CGroupsV2
        if auth or m.image not in ["rhel-8-2", "rhel-8-3"]:
            cpuShares = self.execute(auth, "podman inspect --format '{{.HostConfig.CpuShares}}' busybox-without-publish").strip()
            # podman ≥ 1.8 translates 0 default into actual value
            self.assertIn(cpuShares, ['0', '1024'])

        b.set_val("#containers-containers-filter", "all")

        b.click("a:contains('Console')")
        b.wait_text(".xterm-accessibility-tree > div:nth-child(1)", "/ # ")
        b.focus(".xterm-helper-textarea")
        b.key_press('echo hello\r')
        b.wait_text(".xterm-accessibility-tree > div:nth-child(2)", "hello")
        b.wait_text(".xterm-accessibility-tree > div:nth-child(3)", "/ # ")
        b.wait_text(".xterm-accessibility-tree > div:nth-child(1)", "/ # echo hello")
        b.click('#containers-containers tbody tr:contains("busybox-without-publish") + tr button:contains(Stop) + button')
        b.click("div.pf-c-dropdown.pf-m-expanded ul li:nth-child(1) a")
        b.wait_text(".xterm-accessibility-tree > div:nth-child(3)", "/ #  disconnected ")
        sha = self.execute(auth, "podman inspect --format '{{.Id}}' busybox-without-publish").strip()
        self.check_container(sha, auth, ['busybox-without-publish', 'busybox:latest', '/bin/sh', 'exited'])
        b.click('#containers-containers tbody tr:contains("busybox-without-publish") + tr button:contains(Start)')
        self.check_container(sha, auth, ['busybox-without-publish', 'busybox:latest', '/bin/sh', 'running'])
        b.wait_text(".xterm-accessibility-tree > div:nth-child(1)", "/ # ")
        b.click('#containers-containers tbody tr:contains("busybox-without-publish") + tr button:contains(Stop) + button')
        b.click("div.pf-c-dropdown.pf-m-expanded ul li:nth-child(1) a")
        self.check_container(sha, auth, ['busybox-without-publish', 'busybox:latest', '/bin/sh', 'exited'])
        b.click('#containers-containers tr:contains("busybox-without-publish")')

        b.set_input_text('#containers-filter', 'tty')
        self.check_containers(["busybox-with-tty"], ["busybox-without-publish"])
        self.check_images([], ["busybox:latest", "alpine:latest", "registry:2"])
        b.set_input_text('#containers-filter', 'busy')
        self.check_containers(["busybox-with-tty", "busybox-without-publish"], [])
        self.check_images(["busybox:latest"], ["alpine:latest", "registry:2"])
        b.set_input_text('#containers-filter', 'alpine')
        self.check_containers([], ["busybox-with-tty", "busybox-without-publish"])
        self.check_images(["alpine:latest"], ["busybox:latest", "registry:2"])
        b.set_input_text('#containers-filter', '')
        self.check_containers(["busybox-with-tty", "busybox-without-publish"], [])
        self.check_images(["busybox:latest", "alpine:latest", "registry:2"], [])

        b.set_val("#containers-containers-filter", "all")
        self.check_container(sha, auth, ['busybox-without-publish', 'busybox:latest', '/bin/sh', 'exited'])
        b.click('#containers-containers tr:contains("busybox-without-publish")')
        b.click("a:contains('Console')")
        b.wait_text("span.empty-message", "Container is not running")

        b.click('#containers-images tbody tr:contains("busybox:latest") td.listing-ct-toggle')
        b.click("#containers-images tbody tr:contains('busybox:latest') + tr.listing-ct-panel a:contains('Used By')")
        b.wait_visible("#containers-images tbody tr:contains('busybox:latest') + tr div.listing-ct-body tbody th:contains('busybox-without-publish')")
        b.wait_visible("#containers-images tbody tr:contains('busybox:latest') + tr div.listing-ct-body tbody th:contains('busybox-with-tty')")

        b.click('#containers-images tbody tr:contains("alpine:latest") td.listing-ct-toggle')
        b.click("#containers-images tbody tr:contains('alpine:latest') + tr.listing-ct-panel a:contains('Used By')")
        b.wait_visible("#containers-images tbody tr:contains('alpine:latest') + tr div.listing-ct-body thead.listing-ct-empty td:contains('No containers are using this image')")

        b.set_input_text('#containers-filter', 'foobar')
        b.wait_present('#containers-containers thead tr td:contains("No containers that match the current filter")')
        b.wait_present('#containers-images thead tr td:contains("No images that match the current filter")')
        b.set_input_text('#containers-filter', '')
        self.execute(auth, "podman rmi -f $(podman images -q)")
        b.wait_present('#containers-containers thead tr td:contains("No containers")')
        b.set_val("#containers-containers-filter", "running")
        b.wait_present('#containers-containers thead tr td:contains("No running containers")')
        b.wait_present('#containers-images thead tr td:contains("No images")')

    def check_content(self, type, present, not_present):
        b = self.browser
        for item in present:
            b.wait_visible('#containers-{0} tbody tr:contains({1})'.format(type, item))
        for item in not_present:
            b.wait_not_present('#containers-{0} tbody tr:contains({1})'.format(type, item))

    def check_containers(self, present, not_present):
        self.check_content("containers", present, not_present)

    def check_images(self, present, not_present):
        self.check_content("images", present, not_present)

    def check_container(self, row_id, auth, expected_strings):
        """Check the container with row_name has the expected_string shown in the row"""
        sel = "#containers-containers tbody tr[data-row-id={0}{1}]".format(row_id, auth).lower()
        b = self.browser
        for str in expected_strings:
            b.wait_in_text(sel, str)

    def filter_containers(self, value):
        """Use dropdown menu in the header to filter containers"""
        b = self.browser
        b.set_val("#containers-containers-filter", value)

    def confirm_modal(self, key_type):
        """Wait for the pop up window and click the button with className as key_type"""
        b = self.browser
        b.wait_present(".modal-dialog div")
        b.wait_present(".modal-dialog div .%s" % key_type)
        b.click(".modal-dialog div .%s" % key_type)
        b.wait_not_present(".modal-dialog div .%s" % key_type)

if __name__ == '__main__':
    testlib.test_main()
