#! /bin/bash
# This is the expected entry point for Cockpit CI; will be called without
# arguments but with an appropriate $TEST_OS

set -eu

export RUN_TESTS_OPTIONS=--track-naughties

TEST_SCENARIO=${TEST_SCENARIO:-}

if [ "$TEST_SCENARIO" == "devel" ]; then
    export TEST_COVERAGE=yes
fi

make codecheck
make check
make po/podman.pot
