#! /bin/bash
# This is the expected entry point for Cockpit CI; will be called without
# arguments but with an appropriate $TEST_OS

set -eu

export RUN_TESTS_OPTIONS=--track-naughties

make codecheck
make check
make po/podman.pot
