#! /bin/bash
# This is the expected entry point for Cockpit CI; will be called without
# arguments but with an appropriate $TEST_OS

set -eu

export RUN_TESTS_OPTIONS=--track-naughties

TEST_SCENARIO=${TEST_SCENARIO:-}

if [ "$TEST_SCENARIO" == "devel" ]; then
    export TEST_COVERAGE=yes
fi

# Workaround broken podman pasta on Fedora-CoreOS https://bugzilla.redhat.com/show_bug.cgi?id=2277954
if [ "$TEST_OS" == "fedora-coreos" ]; then
    export RUN_TESTS_OPTIONS="${RUN_TESTS_OPTIONS} --enable-network"
fi

make codecheck
make check
make po/podman.pot
