#!/bin/sh
# image-customize script to enable cockpit in test VMs
# The application RPM will be installed separately
set -eu

# HACK - see https://github.com/containers/libpod/commit/59353b4dce692df0fb22a15427abbaafad58050e
if [ -f /usr/lib/systemd/user/io.podman.socket ]; then
    sed -i '/^Also/d' /usr/lib/systemd/user/io.podman.socket
fi

systemctl enable cockpit.socket io.podman.socket

# don't force https:// (self-signed cert)
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if type firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --add-service=cockpit --permanent
fi

# grab a few images to play with; tests run offline, so they cannot download images
podman pull docker.io/busybox
podman pull docker.io/alpine
podman pull docker.io/registry:2

sudo -i -u admin bash << EOF
podman pull docker.io/busybox
podman pull docker.io/alpine
podman pull docker.io/registry:2
EOF

# HACK: https://bugzilla.redhat.com/show_bug.cgi?id=1782435
# segfaults at boot and breaks every test due to unexpected messages
# Happens only on RHEL-8-2, but we can safely just remove it everywhere
rm /usr/libexec/virt-what-cpuid-helper
