#!/bin/sh
# image-customize script to prepare a bots VM for cockpit-podman testing
set -eu

if grep -q ID.*debian /usr/lib/os-release; then
    # Debian does not enable user namespaces by default
    echo kernel.unprivileged_userns_clone = 1 > /etc/sysctl.d/00-local-userns.conf
    systemctl restart systemd-sysctl

    # disable services that get in the way of /var/lib/containers
    if systemctl is-enabled docker.service; then
        systemctl disable docker.service
    fi

    # tuned is installed for testing cockpit; but it causes funny bugs, and we are not testing this here
    # https://launchpad.net/bugs/1774000 https://launchpad.net/bugs/1925765
    systemctl disable tuned
fi

# don't force https:// (self-signed cert)
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if type firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --add-service=cockpit --permanent
fi

. /usr/lib/os-release

# HACK: this eventually goes into https://github.com/cockpit-project/bots/blob/main/images/scripts/lib/podman-images.setup; remove
# this once all our images are rebuilt

podman pull quay.io/prometheus/busybox
podman pull quay.io/jitesoft/alpine
podman pull quay.io/libpod/registry:2.8
# the tests expect the image to be called differently, so re-tag them
podman tag quay.io/prometheus/busybox localhost/test-busybox
podman rmi quay.io/prometheus/busybox
podman tag quay.io/jitesoft/alpine localhost/test-alpine
podman rmi quay.io/jitesoft/alpine
podman tag quay.io/libpod/registry:2.8 localhost/test-registry
podman rmi quay.io/libpod/registry:2.8

# Remove extra images, tests assume our specific set
# Since 4.0 podman now ships the pause image
podman images --format '{{.Repository}}:{{.Tag}}' | grep -Ev 'localhost/test-|pause|cockpit/ws' | xargs -r podman rmi -f

# copy images for user podman tests; podman insists on user session
loginctl enable-linger $(id -u admin)
images=$(podman images --format '{{.Repository}}:{{.Tag}}')
for img in $images; do
	podman save  $img | sudo -i -u admin podman load
done
	loginctl disable-linger $(id -u admin)

# 15minutes after boot tmp files are removed and podman stores some tmp lock files
systemctl disable --now systemd-tmpfiles-clean.timer
systemctl --global disable systemd-tmpfiles-clean.timer
