specfile_path: cockpit-podman.spec
synced_files:
  - cockpit-podman.spec
upstream_package_name: cockpit-podman
downstream_package_name: cockpit-podman
actions:
  post-upstream-clone: make cockpit-podman.spec
  # reduce memory consumption of webpack in sandcastle container
  # https://github.com/packit/sandcastle/pull/92
  # https://medium.com/the-node-js-collection/node-js-memory-management-in-container-environments-7eb8409a74e8
  create-archive: make NODE_OPTIONS=--max-old-space-size=500 dist-gzip
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-all
