specfile_path: cockpit-podman.spec
actions:
  create-archive: make dist-gzip
  post-upstream-clone: make cockpit-podman.spec
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all-x86_64
  trigger: pull_request
