specfile_path: cockpit-podman.spec
upstream_package_name: cockpit-podman
downstream_package_name: cockpit-podman
actions:
  post-upstream-clone: make cockpit-podman.spec
  create-archive: make dist
srpm_build_deps:
  - make
  - npm
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-35
      - fedora-36
      - fedora-development
      - centos-stream-9-x86_64

  - job: copr_build
    trigger: release
    metadata:
      owner: "@cockpit"
      project: "cockpit-preview"
      preserve_project: True
      targets:
      - fedora-35
      - fedora-36
      - fedora-development
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64
