upstream_project_url: https://github.com/cockpit-project/cockpit-podman
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/cockpit-podman
specfile_path: cockpit-podman.spec
upstream_package_name: cockpit-podman
downstream_package_name: cockpit-podman
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

actions:
  post-upstream-clone: make cockpit-podman.spec
  create-archive: make dist

srpm_build_deps:
  - make
  - npm

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-40
    - fedora-41
    - fedora-latest-aarch64
    - fedora-development
    - centos-stream-9-x86_64
    - centos-stream-9-aarch64
    - centos-stream-10

  - job: tests
    trigger: pull_request
    targets:
      - fedora-40
      - fedora-41
      - fedora-latest-aarch64
      - fedora-development
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-10

  - job: copr_build
    trigger: release
    owner: "@cockpit"
    project: "cockpit-preview"
    preserve_project: True
    actions:
      post-upstream-clone: make cockpit-podman.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit-podman/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@cockpit"
    project: "main-builds"
    preserve_project: True

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-development
      - fedora-40
      - fedora-41

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-development
      - fedora-40
      - fedora-41

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-40
      - fedora-41
