#!/usr/bin/env node

var path = require('path');
var fs = require('fs');
var process = require('process');
var webpack = require('webpack');
var config = require('./webpack.config.js');

webpack(config, function (err, stats) {
    if (err) {
        console.log(JSON.stringify(err));
        process.exit(1);
        return;
    }

    var inputs = [ ];
    stats.compilation.fileDependencies.forEach(function(file) {
        inputs.push(path.relative(process.cwd(), file));
    });
    fs.writeFileSync('webpack.inputs', inputs.join("\n") + "\n");
});
